apiVersion: apps/v1
kind: Deployment
metadata:
  name: "frontend-deployment"
  namespace: "2048-game"
spec:
  selector:
    matchLabels:
      app: "frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: "frontend"
    spec:
      containers:
      - image: 767397737394.dkr.ecr.us-east-2.amazonaws.com/navneet-cicd:4
        imagePullPolicy: Always
        name: "frontend"
        ports:
        - containerPort: 80
